name: Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Bump version'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Bump version
        id: bump-version
        run: |
          npm version ${{ github.event.inputs.version_type }}
          echo "::set-output name=version::v$(node -p \"require('./package.json').version\")"

      - name: Build library
        run: npm run build

      - name: Push changes
        run: |
          git push origin HEAD:main --follow-tags

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish
